### ISSUE TITLE
Nunjuck templates are reloaded earlier then are compiled

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#133] opened 2017-02-10 09:45 UTC
Do you have the same issue?

On other projects with swig templates solved with `gulp-wait`. Currently I am testing this on KB project. If it will work for me, I will merge it here also.

**Comment by ronaldruzicka** [comment] 2017-02-10 10:06
Yes, but not always, usually I have to manually refresh again to see the changes in HTML, but sometimes it works properly.

**Comment by janpanschab** [comment] 2017-02-10 11:00
Yes, and that’s why I want to add a short delay before reload by `browserSync`.

**Comment by kettanaito** [comment] 2017-02-13 11:22
I would suggest to try:
* Different BrowserSync reloading methods. There is `bs.reload()` and `bs.stream()` (the one we use now), and there may be more. I remember digging into BrowserSync docs, and all of them seem to have quite specific usage, maybe we are just using a wrong one
* Rather rely on callback from `nunjucks.compile()` method, it might be a possible that pipeline continues before templates are fully compiled. In this case proper callback should help

I personally never experienced this issue, so I would like to test it if I have a spare minute.

**Comment by vbulant** [comment] 2017-04-11 16:16
@janpanschab any update from the KB project?

**Comment by janpanschab** [comment] 2017-04-12 07:03
No problems on KB. Looks like its fixed. 
What about @ronaldruzicka on Walmark?

**Comment by ronaldruzicka** [comment] 2017-04-12 10:25
@janpanschab I'm not using Artem's solution on Walmark, I manually reload so far 😅

**Comment by vbulant** [comment] 2017-04-12 10:36
OK so is there actually anyone experiencing the issue?
If not, I suggest closing the issue and creating the new one once we can reproduce it.

**Comment by ronaldruzicka** [comment] 2017-04-12 11:20
Well we have the problem, I usually (90% of all changes) have to reload the `.nunj` template to update the HTML. CSS works normally. So if the solution on KB works, let's use it

**Comment by ronaldruzicka** [comment] 2017-04-12 11:54
Ok, so I tried `.pipe(browserSync.reload({stream: true}));` and it works really nice and quite fast. So I think we can change our `.pipe(browserSync.stream({ once: true }));` for it. Because time to time it didn't reload anything and I had a white screen until manual reload.

On the other hand I just noticed, that one small change in one template reloads all pages, which in bigger project could take longer time
```
[13:47:10] Starting 'tpl'...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] 7 files changed (index.html, page-checkout.html, page-header.html, page-login.html, page-product-categories.html, product-details.html, tabs.html)
[13:47:10] Finished 'tpl' after 356 ms
```
But I'm not sure if it can be set up to reload just the changed files

**Comment by kettanaito** [comment] 2017-04-17 07:57
Having dug into BrowserSync documentation I assume this can cause the issue:
```js
// gulp/tasks/serve.js@12
    const baseDir = DEVELOPMENT ? [
        config.DEVELOPMENT_BASE,
        config.BUILD_BASE,
        config.NPM,
        config.STYLEGUIDE_BASE

    ] : config.BUILD_BASE;
```
These are the directories BrowserSync is watching and subsequently reacts (refreshes the page/appends the resources) on changes. For me it was always unclear why do we serve source directories, when we never use any source files directly (SASS -> CSS, ES5/6 -> JS, NUNJ -> TPL). 

## What happens
I believe that BrowserSync watcher gets triggered once you change source files (TPL) under `DEVELOPMENT_BASE` folder. This is why we do not have proper reloading.

## Solution
I would suggest to serve only `BUILD_BASE` directory. Needs to be tested, but should eliminate the issue without providing additional tools and workarounds. This will make BrowserSync to watch changes only in build directory, therefore `TPL -> HTML -> trigger` should be a proper chain.

Of course, I would like to her why do we serve it this way in the first place.

**Comment by ronaldruzicka** [comment] 2017-04-17 10:08
@kettanaito I also don't understand why we should serve the `DEVELOPMENT_BASE`, but anyway it didn't work, it was one change late. And unfortunately neither the `.pipe(browserSync.reload({stream: true}));` works properly, just sometimes. So probably so far only `gulp-wait` can solve this issue, as is in KB project: 
```js
.pipe(wait(1000))
.pipe(browserSync.stream({ once: true }));
```
but for me it had to be at least `.pipe(wait(1500))`

**UPDATE**: 

1. can we maybe use [`nunjucks.configure` with `watch` option](https://mozilla.github.io/nunjucks/api.html#configure)?

2. or maybe we can get inspired from [sitecore demo](https://github.com/Sitecore/Sitecore.Demo.Theme/blob/master/gulpfile.babel.js) setup they have for frontend Habitat theme

**Comment by kettanaito** [comment] 2017-04-17 17:11
@ronaldruzicka is there a repo to reproduce this issue (KB, etc.)?

**Comment by ronaldruzicka** [comment] 2017-04-17 17:20
@kettanaito I suppose, that any project using our gulp dev stack, but you can try Klub Zdravi, we have the issue there

**Comment by kettanaito** [comment] 2017-04-30 12:11
@ronaldruzicka @janpanschab Try [reloadDelay](https://www.browsersync.io/docs/options#option-reloadDelay) from BrowserSync options. Should help in this situation and save from adding extra dependency to the devstack.

However, I think this is more a work-around rather than actual solution. My gist still goes with the issue that we serve development files, changes in which trigger reload.

**Comment by ronaldruzicka** [comment] 2017-05-02 08:35
@kettanaito Thanks, it looks like `reloadDelay` works!
Regarding your solution, I tried to change the it to serve production files and it didn't work for me. Did you try that solution? Did it work for you?

**Comment by kettanaito** [comment] 2017-05-02 09:40
@ronaldruzicka I'm glad it worked!

No, I haven't tried removing dev files from served. But I really think we should, can't find a reason to do so, to be honest.

**Comment by janpanschab** [comment] 2017-05-15 18:46
Still facing the same issue. Gulp wait looks like good enough solution. If I’m right, reloadDelay is possible to use only for whole browserSync setup. Not for one task only. In that case, gulp wait is better for me.

**Comment by ronaldruzicka** [comment] 2017-06-30 09:29
Hey, I think I just solved this issue! According to [documentation](https://browsersync.io/docs/gulp/#gulp-reload) I created two tasks for templates. One for compiling and another one for checking if the compile is done and then reloads the browser.

**task to compile (our old `tpl`):**
```js
gulp.task('tpl-compile', () => {
   ...compile logic 
});
```

**task to wait and reload browser:**
```js
gulp.task('tpl', ['tpl-compile'], (done) => {
    browserSync.reload();
    done();
});
```
**and the output is:**
![screen shot 2017-06-30 at 11 26 45](https://user-images.githubusercontent.com/20684387/27729715-1c53ca48-5d87-11e7-8714-94f7029c78ba.png)

So you can see that it reloads the browser only when templates are ready, so you don't have to refresh the browser manually anymore.

What do you think about this solution?

**Comment by vbulant** [comment] 2017-07-11 09:16
Works like a charm! Thanks 🤗

**Closed as completed** 2017-07-12 08:10 UTC
Labels: bug
